version: "3.8"
services:
  app:
    container_name: frontend
    environment:
      - "PORT=${PORT}"  
    build: .
    command: npm run dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules